### ISSUE TITLE
invalid version string for composer_packages multiple specific package update

### ISSUE THREAD

**Issue by sts-ryan-holton** [kawax/composer-update-action#429]
`COMPOSER_PACKAGES` can't update packages because of invalid version string. How to update multiple specific pacakges, here's my config:

```
name: composer update

on:
  schedule:
    # At minute 10 past hour 8, 10, 11, 13, 14, 15, 16, 17, and 18 on every day-of-week from Monday through Friday.
    - cron: '10 8,10,11,13,14,15,16,17,18 * * 1-5'

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: composer update action
        uses: kawax/composer-update-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_UPDATE_GITHUB_PERSONAL_ACCESS_TOKEN }}
          GIT_COMMIT_PREFIX: '[github action composer update]: '
          COMPOSER_PACKAGES: 'company/pkg-package-one company/pkgi-package-two'
```
